
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class Airplain
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Airplain()
    {

        this.AirplainCabinDetails = new HashSet<AirplainCabinDetail>();

        this.Flights = new HashSet<Flight>();

    }


    public int Airplain_ID { get; set; }

    public string Airplain_Type { get; set; }

    public Nullable<int> Total_Seats { get; set; }

    public Nullable<int> Airline_ID { get; set; }



    public virtual Airline Airline { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AirplainCabinDetail> AirplainCabinDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Flight> Flights { get; set; }

}

}
