
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class AirplainCabinDetail
{

    public int Airplain_ID { get; set; }

    public int Cabin_ID { get; set; }

    public Nullable<int> Seats { get; set; }

    public Nullable<int> Price { get; set; }

    public int Flight_ID { get; set; }

    public Nullable<int> InsurancePrice { get; set; }



    public virtual Airplain Airplain { get; set; }

    public virtual Cabin Cabin { get; set; }

    public virtual Flight Flight { get; set; }

}

}
