
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class booking
{

    public int booking_id { get; set; }

    public Nullable<int> booking_car_id { get; set; }

    public Nullable<int> booking_customer_id { get; set; }

    public string booking_rent_date { get; set; }

    public string booking_return_date { get; set; }

    public string booking_number_of_days { get; set; }

    public string booking_total_amount { get; set; }

}

}
