//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNewUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int booking_id { get; set; }
        public Nullable<int> booking_car_id { get; set; }
        public Nullable<int> booking_customer_id { get; set; }
        public string booking_rent_date { get; set; }
        public string booking_return_date { get; set; }
        public string booking_number_of_days { get; set; }
        public string booking_total_amount { get; set; }
    
        public virtual car car { get; set; }
        public virtual customer customer { get; set; }
    }
}
