//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirNewUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car()
        {
            this.bookings = new HashSet<booking>();
            this.CarImages = new HashSet<CarImage>();
        }
    
        public int car_id { get; set; }
        public Nullable<int> car_category_id { get; set; }
        public string car_name { get; set; }
        public string car_number { get; set; }
        public string car_daily_price { get; set; }
        public string car_brand_name { get; set; }
        public string car_color { get; set; }
        public string car_manufacture_date { get; set; }
        public string car_milage { get; set; }
        public string car_horse_power { get; set; }
        public string car_insurance_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarImage> CarImages { get; set; }
    }
}
