//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int car_id { get; set; }
        public Nullable<int> car_category_id { get; set; }
        public string car_name { get; set; }
        public string car_number { get; set; }
        public string car_daily_price { get; set; }
        public string car_brand_name { get; set; }
        public string car_color { get; set; }
        public string car_manufacture_date { get; set; }
        public string car_milage { get; set; }
        public string car_horse_power { get; set; }
        public string car_insurance_number { get; set; }
    }
}
