
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class car
{

    public int car_id { get; set; }

    public Nullable<int> car_category_id { get; set; }

    public string car_name { get; set; }

    public string car_number { get; set; }

    public string car_daily_price { get; set; }

    public string car_brand_name { get; set; }

    public string car_color { get; set; }

    public string car_manufacture_date { get; set; }

    public string car_milage { get; set; }

    public string car_horse_power { get; set; }

    public string car_insurance_number { get; set; }

}

}
