
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class CountryCityAirport
{

    public int Country_City_Airport_ID { get; set; }

    public Nullable<int> Country_ID { get; set; }

    public Nullable<int> City_ID { get; set; }

    public Nullable<int> Airport_ID { get; set; }



    public virtual Airport Airport { get; set; }

    public virtual City City { get; set; }

    public virtual Country Country { get; set; }

}

}
