
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class customer
{

    public int customer_id { get; set; }

    public string customer_firstname { get; set; }

    public string customer_lastname { get; set; }

    public string customer_phone { get; set; }

    public string customer_dob { get; set; }

}

}
