
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class FlightSeat
{

    public int FlightSeat_ID { get; set; }

    public Nullable<int> Flight_ID { get; set; }

    public string Seat_ID { get; set; }

    public Nullable<bool> Seat_TF { get; set; }



    public virtual Flight Flight { get; set; }

}

}
