//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_Order_Detail
    {
        public Nullable<int> Order__ID { get; set; }
        public Nullable<int> Hotel_ID { get; set; }
        public Nullable<int> Room_Id { get; set; }
        public string Room_Category { get; set; }
        public Nullable<int> Room_Quantity { get; set; }
        public Nullable<System.DateTime> Check_In_Date { get; set; }
        public Nullable<System.DateTime> Check_Out_Date { get; set; }
        public Nullable<bool> Food { get; set; }
        public int Detail_ID { get; set; }
    
        public virtual HotelOrder HotelOrder { get; set; }
    }
}
