//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelOrder()
        {
            this.Hotel_Order_Detail = new HashSet<Hotel_Order_Detail>();
        }
    
        public Nullable<int> Hotel_ID { get; set; }
        public string Hotel_Name { get; set; }
        public int Order_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public string Member__Email { get; set; }
        public string Member__Gender { get; set; }
        public string Member__Phone { get; set; }
        public string Member__En_FirstName { get; set; }
        public string Member__En_LastName { get; set; }
        public Nullable<int> Living_Number_of_people { get; set; }
        public string CashMethod { get; set; }
        public Nullable<int> Total_Price { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_Order_Detail> Hotel_Order_Detail { get; set; }
        public virtual Member Member { get; set; }
    }
}
