
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class MemberViewDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MemberViewDetail()
    {

        this.MemberPhotoes = new HashSet<MemberPhoto>();

    }


    public int MemberViewDetail_ID { get; set; }

    public Nullable<int> View_ID { get; set; }

    public Nullable<decimal> Score { get; set; }

    public string Comment { get; set; }

    public Nullable<int> Member_ID { get; set; }



    public virtual Member Member { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MemberPhoto> MemberPhotoes { get; set; }

    public virtual View View { get; set; }

}

}
