
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class Passenger
{

    public int Passenger_ID { get; set; }

    public Nullable<int> Ticket_ID { get; set; }

    public string Passenger_En_FirstName { get; set; }

    public string Passenger_En_LastName { get; set; }

    public string Passenger_Gender { get; set; }

    public string Passenger_Passport { get; set; }

    public Nullable<System.DateTime> Death_Of_Expiry { get; set; }

    public Nullable<System.DateTime> Death_Of_Birth { get; set; }

    public string Passenger_Type { get; set; }



    public virtual Order Order { get; set; }

}

}
