
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AirTicket
{

using System;
    using System.Collections.Generic;
    
public partial class ViewPhoto
{

    public int ViewPhoto_ID { get; set; }

    public Nullable<int> View_ID { get; set; }

    public byte[] ViewPhoto1 { get; set; }



    public virtual View View { get; set; }

}

}
